name: Continuous Deployment

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write

    strategy:
      matrix:
        item:
          [
            { df_path: ./coder/reveal-js, image: "${{ github.repository}}/coder-reveal-js" },
            { df_path: ./rust/musl-builder, image: "${{ github.repository}}/rust-musl-builder" },
            { df_path: ./rust/musl-watch, image: "${{ github.repository}}/rust-musl-watch" },
            { df_path: ./node/alpine-dev, image: "${{ github.repository}}/node-alpine-dev" },
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.item.image }}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ matrix.item.df_path }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: ${{ github.event_name != 'workflow_dispatch' && 'type=gha,mode=max' || '' }}
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        if: github.event_name != 'pull_request'
        with:
          subject-name: ${{ env.REGISTRY }}/${{ matrix.item.image }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        if: github.event_name == 'pull_request'
        with:
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() && github.event_name == 'pull_request' }}
        with:
          sarif_file: "trivy-results.sarif"
